### PR TITLE
Support for relative paths

### PR DESCRIPTION
**Pull request by mitar**
Now relative paths used in requirejs also work. One can do things like:

```
define('lodash-modern/objects/keys',['../internals/isNative', './isObject', '../internals/shimKeys'], function(isNative, isObject, shimKeys) {
```

And expect it to work correctly. :-)

### CODE REVIEW

**Comment by apendua** [comment]
@mitar Thank you for this one. I also created a `devel` branch and changed quite a few things, so if you have some time please take a look.

**Comment by mitar** [comment]
I tested on our packages we are using and it seems `devel` branch works as well. Good job. Thanks.

**Comment by apendua** [comment]
@mitar Thank you for the feedback. Expect a version bump in the nearest future.

**Comment by mitar** [comment]
Great. Please tell when you release.

**Pull request merged**
